### PR TITLE
Add research pages

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description

Add research/project/events content to website.

## Todos

 - [x] Add templates for research and project content files
 - [x] Add research content (text + figures)
    - Binding Site Comparison
    - Pharmacophore Modeliing 
    - Kinase-Focused Fragment Library
    - TeachOpenCADD
 - [x] Add projects content (text + figures)
    - ratar
    - kissim
    - TeachOpenCADD
    - T2F-Pharm
    - T2F-Flex
    - KinFragLib
 - [x] Add install details and resources to README
 - [x] Revise project descriptions (ready to go) and TOCs (ready to go, only T2F-Flex and ratar will be added later)

## Questions
 - [x] Events do not show up in main menu - why? > Because `publishdate` tag in markdown header was set to future.

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by jaimergp** [comment]
This is looking amazing! Thank you so much! I propose the following plan:

1. Merge as soon as possible. For this I need to:
    - [ ] Create templates (project, events)
    - [ ] Find out how to include additional pages manually
2. We will automate it the generation later so it's easier to maintain.

Do you agree?

**Comment by jaimergp** [comment]
Oops, my timestamps are wrong but I did add some commits there.

Basically we have now `archetypes` so all you have to do to create a new project is:

```
hugo new projects/my_project.md
```

which will create the specified file using the template found under `archetypes/` (it detects which one to use based on the path). This has the added benefit of having the date added automatically and not having to copy things over.

Next iteration will cover how to use the frontmatter metadata (now commented out) to replace the sections below.

**Comment by jaimergp** [comment]
I added a `shortcode` (kind of Hugo "functions") to embed pages within pages. Usage:

```
{{% content "path/to/otherpage.md" %}}

```

Path must be relative to `/content`. For example to link to `/content/projects/kissim.md`, you use:

```
{{% content "projects/kissim.md" %}}
```

**Comment by jaimergp** [comment]
@dominiquesydow can you review if this is what you had in mind?

**Comment by dominiquesydow** [comment]
This looks great! Thank you for setting up the `archetypes` and `shortcodes`!

**Comment by jaimergp** [comment]
Merging to an intermediary branch named `launch`, in which I will prepare the new changes.

**Pull request merged**
