### PR TITLE
Add struc2drug contact details + organizers

### PR DESCRIPTION
**Pull request by dominiquesydow**
Update struc2drug website

- Add back struc2drug contact details (Twitter and organizer email address)
- Add past and future organizers with contact details

Also: Fix some broken links.

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@AndreaVolkamer could you provide me please with an updated link for
https://www.mi.fu-berlin.de/bioinf/stud/bachelor/abv/projektmanagement/SWP_projekte/Structural_Alignment.html

See CI fail: https://github.com/volkamerlab/volkamerlab_org/runs/4430459037?check_suite_focus=true#step:4:265

**Comment by AndreaVolkamer** [comment]
@dominiquesydow I guess the FU takes the links down after some time.
So let us rephrase the respective sentence:

> Software and project management (60102613): Structural Alignment with OpenCADD WS20/21 (continued from WS19/20). More details about OpenCADD.

to this:
> Software and project management (60102613): Structural Alignment with OpenCADD WS20/21 (continued from WS19/20). [More details about OpenCADD](https://volkamerlab.org/projects/opencadd/) and the results of the [structural alignment](https://opencadd.readthedocs.io/en/latest/superposition.html) project.

**Comment by dominiquesydow** [comment]
Hi @corey-taylor, I already have the ok from Kristina - could you please check if you approve this PR?

**Review by corey-taylor — APPROVED** [review]
Good to go from my perspective.

**Pull request merged**
