### PR TITLE
Corrected 404 (maxsmi) and other parts

### PR DESCRIPTION
**Pull request by corey-taylor**
This specific PR is to correct a 404 introduced here (https://github.com/volkamerlab/volkamerlab_org/commit/4f340eff64dab13c624fc63260add27d5ace16aa) but also a commit I accidentally made to the site's main repo ( https://github.com/volkamerlab/volkamerlab_org/commit/1bb0598e85222afa484d30b6f9e9543746aab579). Please review the changes on that commit too and I'll add changes you suggest to this PR from now on.

You'll see in the commit which specific files have been edited but to summarise the changes:

- Alex added to team page (https://volkamerlab.org/team/)
- Summary of Alex's project added to Research -> Machine Learning -> Historical Virtual Control Groups (https://volkamerlab.org/research/machine-learning/virtual_control_groups/)

### CODE REVIEW

**Comment by AndreaVolkamer** [comment]
@corey-taylor thanks for taking care of the addition of Alexander and his project.

Could you adapt a few things please:
* Reorder to have him appear on the teams page after Dominique, before Andrea
* Enter his project on the Research->ML page after Maxsmi
* Have only this part of the text appear as summary: 
> Historical Virtual Control Groups: one step forward into the future of animal testing in toxicology. Our goal is to reduce the number of animals used in experiments Starting with an exceptional dataset provided by members of the eTRANSAFE consortium we start the journey into the future of animal testing via derivation and incorporation of virtual control groups in animal testing approaches and thus enabling a 3R strategy.
* Check that the project also appears under 'see all projects'
* On the project site itself:
    * Add link to Alexander and me back to the teams page
    * Take the publication out of the publications section (that one is meant more for Alexander's own publications. Directly link the reference instead where it appears
    * Delete all titles (Dr.) from the people, I think we don't have them on any other page
* Note: I did not check the text in every detail, just assumed it will be fine.

**Review by AndreaVolkamer — CHANGES_REQUESTED** [review]
@corey-taylor see comment above.

**Comment by corey-taylor** [comment]
All done. Also added image from the document he provided.

**Comment by AndreaVolkamer** [comment]
@corey-taylor Thanks a lot.

One minor thing I observed: 
On the [ML methods overview page](https://deploy-preview-80--admiring-blackwell-3e6756.netlify.app/research/machine-learning/), the title of Alexander's project appears without any information now and nor `Read more` button.

Otherwise ready to be merged!

**Review by AndreaVolkamer — APPROVED** [review]
@corey-taylor see last comment above. 

Generally ready to be merged then.

**Comment by corey-taylor** [comment]
> @corey-taylor Thanks a lot.
> 
> One minor thing I observed: On the [ML methods overview page](https://deploy-preview-80--admiring-blackwell-3e6756.netlify.app/research/machine-learning/), the title of Alexander's project appears without any information now and nor `Read more` button.
> 
> Otherwise ready to be merged!

Yup. Renamed a file but hadn't updated a link. Fixed now!

**Pull request merged**
