### PR TITLE
AV launch v2

### PR DESCRIPTION
**Pull request by AndreaVolkamer**
Some more fine tuning ....
update/correct
- [x] team page
- [x] welcome text
- [x] software page
- [x] publications
- [x] education
- [x] research lines (wo openkinome)
- [x] projects (wo openkinome)

Todo: 
- [ ] Check with collaborators if they agree on the text and want to be linked!
- [ ] Check all figure captions (and add references if needed)

### CODE REVIEW

**Comment by AndreaVolkamer** [comment]
@jaimergp just tagging you here so you know that I updated the welcome page.

**Comment by AndreaVolkamer** [comment]
@jaimergp I added the links to the repos on the software page, ok?

**Comment by AndreaVolkamer** [comment]
@jaimergp publications fixed

**Comment by jaimergp** [comment]
Note: Current 404s are false positives.

**Comment by AndreaVolkamer** [comment]
@jaimergp Added the education stuff - please have a look since the text is new.
(I did not fix the intro paragraph thing at TeachOpenCADD yet, not sure if you have a respective keyword in place already?)

**Comment by AndreaVolkamer** [comment]
@jaimergp just wondering for teachopencadd, should we leave the API stuff in, or hold it back until the docking is fixed?

**Comment by jaimergp** [comment]
> @jaimergp just wondering for teachopencadd, should we leave the API stuff in, or hold it back until the docking is fixed?

I think the current version has a notice saying that the API stuff is still experimental. Maybe we can include that disclaimer in the website too?

**Comment by AndreaVolkamer** [comment]
@jaimergp I finished the review of the ML research line. Please go ahead and merge - or add - your/all openkinome additions.
Once everything is there, I want to ask each member to go through their pages to see if they agree with everything, and so they can add missing things (e.g. refs in figure captions).

**Pull request merged**
