### PR TITLE
Add KinFragLib blog post

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description

Add blog post on KinFragLib publication in JCIM.

## TODOs

- [x] Add blog post (including all relevant links)
- [x] Render with `hugo serve` to check output

## Questions

None

## Status

- [x] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@AndreaVolkamer - please let me know what you think about this blog post.

**Review by AndreaVolkamer — APPROVED** [review]
Publish as is :)

**Comment by dominiquesydow** [comment]
@jaimergp - do you want to have a look before merging?

**Comment by jaimergp** [comment]
Already did! Go ahead ;)

**Pull request merged**
