### PR TITLE
TK updates

### PR DESCRIPTION
**Pull request by t-kimber**
This PR includes the Maxmsi project to the website and fixes small typos.

@AndreaVolkamer, would you also like to adapt the Alumni tags?

### CODE REVIEW

**Comment by AndreaVolkamer** [comment]
@t-kimber thanks.

Minor remarks:
* can you double check the maxsmi reference, it belongs to volume 1, so I think it should read
> ... Artificial Intelligence in the Life Sciences 1:100014
* on the maxsmi project page: can you add the reference to the figure caption (Figure taken from ...)

And one suggestion:
* I would introduce maxsmi under reasearch/machine learning as own category (same level as DL based VS) not as see also (as kinoml)

**Review by AndreaVolkamer — APPROVED** [review]
@t-kimber added my comments above, I have raised an issue [(#76)](https://github.com/volkamerlab/volkamerlab_org/issues/76) to myself for making the student categories more consistent in the team section, so this PR can be merged independently.

**Comment by t-kimber** [comment]
Thanks @AndreaVolkamer for your review!

> on the maxsmi project page: can you add the reference to the figure caption (Figure taken from ...)

That is a good catch. I will also add the fig. reference in the maxsmi documentation (see https://maxsmi.readthedocs.io/en/latest/).

I've adapted the files wrt to your comments, so I'll merge the PR if that's okay with you.

**Comment by AndreaVolkamer** [comment]
@t-kimber great thanks. Ready to be merged!!!

**Pull request merged**
