### PR TITLE
Update courses & add group photo

### PR DESCRIPTION
**Pull request by hamzaibrahim21**
### TODO 

- [x] Add group photo to index.md
- [x] Push group photo
- [x] Add no available HiWi positions
- [x] Update courses
 - Move Bioinformatics II to previous courses
 - Add CADD course and seminar for next semester

### CODE REVIEW

**Comment by hamzaibrahim21** [comment]
@AndreaVolkamer I've added the group photo instead of the wordcloud photo, but I couldn't push it. The public directory was added to `.gitignore`. Should I remove it from `.gitignore`?

**Review by AndreaVolkamer — COMMENTED** [review]
@hamzaibrahim21 not entirely sure what you mean, shouldn't the images all be here: https://github.com/volkamerlab/volkamerlab_org/tree/update-courses/static/images

**Comment by hamzaibrahim21** [comment]
> @hamzaibrahim21 not entirely sure what you mean, shouldn't the images all be here: https://github.com/volkamerlab/volkamerlab_org/tree/update-courses/static/images

Sorry, my mistake, it should be now uploaded and can be deployed (Y)

**Comment by AndreaVolkamer** [comment]
@hamzaibrahim21 thanks. Can we maybe add it in a way that it scales to the window size?

**Review by AndreaVolkamer — APPROVED** [review]

**Comment by hamzaibrahim21** [comment]
> @hamzaibrahim21 thanks. Can we maybe add it in a way that it scales to the window size?

@AndreaVolkamer I've updated the photo, but it'll be a bit smaller

**Pull request merged**
