### PR TITLE
DaS-MIAME

### PR DESCRIPTION
**Pull request by schallerdavid**
## Description
This PR adds details about the MIAME project to the website. Before merging we need to get approval from John and the Bayer people.

## Todos
- [x] add brief and general description to project page
- [x] extend description with detailed projects
- [x] add link to openkinome page
- [x] add people and essential collaborators
- [x] add more people/collaborators
- [x] add funding info
- [ ] get approval from John
- [x] get approval from Bayer site

## Status
- [ ] ready to go

### CODE REVIEW

**Comment by schallerdavid** [comment]
@jaimergp Andrea suggested to add a link to your and Talia's name that points to the KinoML project. I was not able to add it to the `more:` section without destroying the website. Do you know an easy way to handle this?

**Comment by schallerdavid** [comment]
@AndreaVolkamer Do you have a preferred way of reporting the funding from Bayer? For now there is only the word Bayer in the respective section without any grant number.

**Comment by AndreaVolkamer** [comment]
@schallerdavid thanks for providing the info. I only changed minor things in the text. 
Concerning your questions:
- funding (I made a sentence out of it)
- people: I added KinoML behind Jaime and Talias names, and Miame behind yours in KinoML, not sure either how to add a link to KinoML there (maybe @jaimergp has an easy solution, otherwise we leave it as is)

**Comment by schallerdavid** [comment]
> @schallerdavid thanks for providing the info. I only changed minor things in the text.
> Concerning your questions:
> 
>     * funding: I made a sentence out of it
> 
>     * people: I added KinoML behind Jaime and Talias names, and Miame behind yours in KinoML, not sure either how to add a link to KinoML there (maybe @jaimergp has an easy solution, otherwise we leave it as is)
> 
> 
> And one more side note: Maybe we can shorten the title: "MIAME: Mutation Impact Annotation using Modeling and Evolution"?
> 
> Otherwise it's ready to go I think.

@AndreaVolkamer I agree, the short title looks also better in the projects list. I split the big title. What do you think?

**Comment by schallerdavid** [comment]
> Do we have approval to integrate this as part of the website already? If that's the case I will review the conflicts and merge once everybody agrees this is ready to go!

We are waiting for approval, the email was sent today.

**Comment by schallerdavid** [comment]
I added the requested funding statement from Bayer.

**Comment by AndreaVolkamer** [comment]
@jaimergp we got approval from Bayer side, so we can merge this part.
This also means that the Miame can be commented in again in the launch branch.

**Pull request merged**
