### PR TITLE
AV changes

### PR DESCRIPTION
**Pull request by AndreaVolkamer**
## Description
Work to be done before website launch

## Todos
- [x] update publications
- [x] update team
- [ ] write/update intro
- [ ] order projects into research themes

### CODE REVIEW

**Comment by AndreaVolkamer** [comment]
@jaimergp just wondering if we want to have a 'books' category in publications?

**Comment by AndreaVolkamer** [comment]
Finished update on team.

**Comment by jaimergp** [comment]
> @jaimergp just wondering if we want to have a 'books' category in publications?

We can add a new key-value entry, `kind: article` for papers, reviews, books, poster, etc.

**Comment by AndreaVolkamer** [comment]
@jaimergp I added the new key-value entry kind with article, review and book for now. Maybe it's easiest if you take care of the html part on how to show this on the website?

Also, maybe it would be worth to review and merge this part of my PR already (publications and team are finished for now and somehow independent from the other two open tasks)?

**Pull request merged**
